// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace SinistrosApi.Infrastructure.Persistencia.Migrations
{
    [DbContext(typeof(SinistrosApiDbContext))]
    partial class SinistrosApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SinistrosApi.Domain.Entidades.Apolice", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedNever()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<Guid>("ClienteId")
                    .HasColumnType("uuid")
                    .HasColumnName("cliente_id");

                b.Property<DateOnly>("DataFimVigencia")
                    .HasColumnType("date")
                    .HasColumnName("data_fim_vigencia");

                b.Property<DateOnly>("DataInicioVigencia")
                    .HasColumnType("date")
                    .HasColumnName("data_inicio_vigencia");

                b.Property<string>("NumeroApolice")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)")
                    .HasColumnName("numero_apolice");

                b.Property<string>("Ramo")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("character varying(20)")
                    .HasColumnName("ramo");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("character varying(20)")
                    .HasColumnName("status");

                b.HasKey("Id")
                    .HasName("pk_apolices");

                b.HasIndex("ClienteId")
                    .HasDatabaseName("ix_apolices_cliente_id");

                b.HasIndex("NumeroApolice")
                    .IsUnique()
                    .HasDatabaseName("ix_apolices_numero_apolice");

                b.ToTable("apolices");
            });

            modelBuilder.Entity("SinistrosApi.Domain.Entidades.Cliente", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedNever()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<DateOnly>("DataReferencia")
                    .HasColumnType("date")
                    .HasColumnName("data_referencia");

                b.HasKey("Id")
                    .HasName("pk_clientes");

                b.ToTable("clientes");

                b.OwnsOne("SinistrosApi.Domain.ObjetosDeValor.Documento", "Documento", b1 =>
                {
                    b1.Property<Guid>("ClienteId")
                        .HasColumnType("uuid");

                    b1.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("numero_documento");

                    b1.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("tipo_documento");

                    b1.HasKey("ClienteId");

                    b1.HasIndex("Numero")
                        .IsUnique()
                        .HasDatabaseName("ix_clientes_numero_documento");

                    b1.ToTable("clientes");

                    b1.WithOwner()
                        .HasForeignKey("ClienteId");
                });

                b.OwnsOne("SinistrosApi.Domain.ObjetosDeValor.NomeCompleto", "Nome", b1 =>
                {
                    b1.Property<Guid>("ClienteId")
                        .HasColumnType("uuid");

                    b1.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b1.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("sobrenome");

                    b1.HasKey("ClienteId");

                    b1.ToTable("clientes");

                    b1.WithOwner()
                        .HasForeignKey("ClienteId");
                });

                b.Navigation("Documento").IsRequired();
                b.Navigation("Nome").IsRequired();
            });

            modelBuilder.Entity("SinistrosApi.Domain.Entidades.HistoricoSinistro", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedNever()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<DateTime>("DataAlteracao")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("data_alteracao");

                b.Property<string>("Motivo")
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)")
                    .HasColumnName("motivo");

                b.Property<Guid>("SinistroId")
                    .HasColumnType("uuid")
                    .HasColumnName("sinistro_id");

                b.Property<string>("StatusAnterior")
                    .HasMaxLength(20)
                    .HasColumnType("character varying(20)")
                    .HasColumnName("status_anterior");

                b.Property<string>("StatusNovo")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("character varying(20)")
                    .HasColumnName("status_novo");

                b.HasKey("Id")
                    .HasName("pk_historico_sinistros");

                b.HasIndex("SinistroId")
                    .HasDatabaseName("ix_historico_sinistros_sinistro_id");

                b.ToTable("historico_sinistros");
            });

            modelBuilder.Entity("SinistrosApi.Domain.Entidades.Sinistro", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedNever()
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<Guid>("ApoliceId")
                    .HasColumnType("uuid")
                    .HasColumnName("apolice_id");

                b.Property<DateTime>("DataAbertura")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("data_abertura");

                b.Property<string>("MotivoNegativa")
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)")
                    .HasColumnName("motivo_negativa");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("character varying(20)")
                    .HasColumnName("status");

                b.Property<decimal>("ValorAprovado")
                    .HasColumnType("numeric(18,2)")
                    .HasColumnName("valor_aprovado");

                b.Property<decimal>("ValorEstimado")
                    .HasColumnType("numeric(18,2)")
                    .HasColumnName("valor_estimado");

                b.HasKey("Id")
                    .HasName("pk_sinistros");

                b.HasIndex("ApoliceId")
                    .HasDatabaseName("ix_sinistros_apolice_id");

                b.ToTable("sinistros");
            });

            modelBuilder.Entity("SinistrosApi.Domain.Entidades.Apolice", b =>
            {
                b.HasOne("SinistrosApi.Domain.Entidades.Cliente", null)
                    .WithMany()
                    .HasForeignKey("ClienteId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });

            modelBuilder.Entity("SinistrosApi.Domain.Entidades.HistoricoSinistro", b =>
            {
                b.HasOne("SinistrosApi.Domain.Entidades.Sinistro", null)
                    .WithMany("Historico")
                    .HasForeignKey("SinistroId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("SinistrosApi.Domain.Entidades.Sinistro", b =>
            {
                b.HasOne("SinistrosApi.Domain.Entidades.Apolice", null)
                    .WithMany()
                    .HasForeignKey("ApoliceId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Historico");
            });
#pragma warning restore 612, 618
        }
    }
}
